name = "iptv-m3u"
main = "_worker.js"
compatibility_date = "2023-10-16"

# 配置静态资源绑定
[site]
bucket = "./" # 静态资源目录

[build]
command = "" # 无需构建命令

# 配置路由和数据库
[env.production]
routes = [
  { pattern = "/api/*", script = "_worker" },
  { pattern = "*/*", script = "_worker" }
]

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "f431695090544ae6a9417d316d039e19"